### ISSUE TITLE
How are missing values handled?

### ISSUE THREAD

**Issue by xiaojiemao** [AMLab-Amsterdam/CEVAE#1]
Hi, 

I notice that there are quite a few missing values in the twins dataset. May I ask how they are handled in the experiments in your paper? How do you impute them?

Thanks!

**Comment by clouizos** [comment]
Hi,

Apologies for the late reply, I just saw the issue. 

For the features that had more than 20% missing values we assigned to the missing values a constant number that was the maximum of the existing values + 1. Essentially this creates a separate 'nan category' for those features. For the rest we used a most-frequent imputation strategy.

Hope this helps!
