### ISSUE TITLE
Pre-processing of Twins dataset

### ISSUE THREAD

**Issue by hammer-wang** [AMLab-Amsterdam/CEVAE#4]
Dear Authors,

Thanks for your inspiring work. 

I'm wondering whether you could share more details about the pre-processing procedure for the TWINS dataset. Specifically, did you keep the raw values of the categorical variables or convert them into one-hot encoding? In addition, for the features 'brstate' and
'brstate_reg', did you use both or just one of them?

Thanks a lot! 

Best,
Haozhu

**Comment by uri-sh** [comment]
Dear Haozhu,
We converted the categorical variables with one-hot-encoding.
We used only brstate_reg.
Best,
Uri

**Comment by hammer-wang** [comment]
Dear Uri, 

Thanks a lot for your quick reply. It helps a lot! 

Closing issue.

Best,
Haozhu
